layout_spectrum: 1
color:
  saturation: 0.7042553
  brandStrength: 0.08878837
  lightness: 0.7808511
  rhythmicContrast: 0.7042553
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.7127659
name: Www.logogolfdirect.com
